plugins:
  - jekyll-toc
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
baseurl: "/wayfinding-redesign"
production_url: http://herschelrs.github.io.com/wayfinding-redesign